name: Go Lint and Format

on: pull_request

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Check formatting
      run: |
        gofmt -w .

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply Go formatting and linting fixes
